version: "3"
services:
  pg:
    image: timescale/timescaledb:latest-pg13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  grafana:
    image: grafana/grafana:8.5.3
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=natel-discrete-panel

      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=pg:5432
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=postgres
      - GF_DATABASE_SSL_MODE=disable

      # I set DATASOURCE_DATABASE=w1_dev for development
      - DATASOURCE_DATABASE=${DATASOURCE_DATABASE:-w1}
    
    volumes:
      - ./grafana/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/wakatime.yml:/etc/grafana/provisioning/dashboards/wakatime.yml

  ingester:
    # image: ghcr.io/ruslandoga/wakatime-1:master
    build: .
    restart: unless-stopped

    environment:
      - DATABASE_URL=ecto://postgres:postgres@pg:5432/w1
      # set LOG_LEVEL=info to see more logs
      - LOG_LEVEL=warn 

    ports:
      - 4000:4000

volumes:
  pgdata:
