{
 "title": "Project",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "my-app" }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(day), trunc(extract('epoch' from sum(duration))::numeric / 3600, 2) as hours\nFROM (\n  SELECT\n    $__timeGroup(time, '1d', 0) AS day,\n    last(time, time) - first(time, time) AS duration\n  FROM durations\n  WHERE $__timeFilter(time) AND project='$project'\n  GROUP BY day, duration_id\n  ORDER BY duration_id\n) AS s\nGROUP BY day;"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('sec', sum(duration))\nFROM (\n  SELECT last(time, time) - first(time, time) AS duration\n  FROM durations\n  WHERE $__timeFilter(time) AND project='$project'\n  GROUP BY duration_id\n) AS s;"
    }
   ]
  },
  {
   "title": "Branches",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('sec', sum(duration)) AS duration, branch\nFROM (\n  SELECT branch, last(time, time) - first(time, time) AS duration\n  FROM durations\n  WHERE $__timeFilter(time) AND project='$project'\n  GROUP BY duration_id, branch\n  ORDER BY duration_id\n) AS s\nGROUP BY branch;"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  duration,\n  CASE\n    WHEN language IS NOT NULL THEN language\n    ELSE 'Other'\n  END AS language\nFROM (\n  SELECT date_trunc('sec', sum(duration)) AS duration, language\n  FROM (\n    SELECT language, last(time, time) - first(time, time) AS duration\n    FROM durations\n    WHERE $__timeFilter(time) AND project='$project'\n    GROUP BY duration_id, language\n  ) AS s\n  GROUP BY language\n) AS s\nWHERE duration >= interval '1 sec'\nORDER BY duration DESC;"
    }
   ]
  },
  {
   "title": "Files",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT duration, file\nFROM (\n  SELECT date_trunc('sec', sum(duration)) AS duration, entity as file\n  FROM (\n    SELECT entity, last(time, time) - first(time, time) AS duration\n    FROM durations\n    WHERE $__timeFilter(time) AND type='file' AND project='$project'\n    GROUP BY duration_id, entity\n    ORDER BY duration_id\n  ) AS s\n  GROUP BY entity\n) AS s\nWHERE duration >= interval '1 sec'\nORDER BY duration DESC;"
    }
   ]
  }
 ]
}